name: Selenium TestNG CI with Allure Reports

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: List project structure
        run: ls -R

      - name: Run Maven Tests
        run: mvn clean test -X

      - name: Upload TestNG Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports